export const contentList = [
    {
        title: "嘉定哪里可以洗车？",
        content: "坐标安亭附近，刚提的车，请问哪里洗车便宜，可以长期办卡？",
        userAvatar: "https://picsum.photos/400/400?random=4",
        userName: "TJSheeran",
        publishTime: "2023-11-08 11:35",
        location: "安亭镇",
        answersNum: 66,
        isCollected: true,
        ipLoaction: "上海",
        isFocused: true,
    },
    {
        title: "芋泥香酥鸭嘉定哪里能吃到？",
        content: "小红书上超级火的芋泥香酥鸭嘉定有吗，有友友买到过吗，好想吃，外卖看了一圈没找到。",
        userAvatar: "https://picsum.photos/400/400?random=5",
        userName: "小红书骑手",
        publishTime: "2023-11-19 11:35",
        location: "安亭镇",
        answersNum: 24,
        isCollected: false,
        ipLoaction: "上海",
        isFocused: true,
    },
    {
        title: "安亭财富广场门口停车位收费吗？",
        content: "住在昆山，每天上班在安亭财富广场，请问门口停车收费吗，如果收费的话什么标准呢，长期停的话有没有优惠呀，或者旁边嘉亭荟有没有免费的长期停车位呢？",
        userAvatar: "https://picsum.photos/400/400?random=6",
        userName: "茶百道打工仔",
        publishTime: "2023-11-08 11:35",
        location: "安亭镇",
        answersNum: 36,
        isCollected: false,
        ipLoaction: "上海",
        isFocused: false,
    },
];

